### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by lezoid** [joeshaw/carwings#12]
panic: runtime error: index out of range
Japan 2018 model (40kwh / ZE1 type).

UserLoginRequest.phpHTTP200, and it looks like the value is returned successfully.
The same error occurs even if you delete the URL option.

Is it related to issues #3 and #8?

```

./carwings -debug -region NML -url https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/ -username username -password password update
Logging into Carwings...
POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/InitialApp.php map[initial_app_strings:[hogehoge]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
Date: Mon, 13 May 2019 07:28:47 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

45
{"status":200,"message":"success","baseprm":"hogehoge"}
0



Error loading session from /root/.carwings-session: open /root/.carwings-session: no such file or directory
POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/UserLoginRequest.php map[initial_app_strings:[hogehoge] UserId:[username] Password:[password] RegionCode:[NML]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Mon, 13 May 2019 07:28:47 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

3c1
{"status":200,"EncAuthToken":"Token","CustomerInfo":{"UserId":"username","Language":"ja-JP","Timezone":"Asia\/Tokyo","RegionCode":"NML","OwnerId":"1111111111","EMailAddress":"hoge@hoge.com","Nickname":"username","Country":"JP","VehicleImage":"\/content\/language\/default\/images\/img\/ph_car.jpg","UserVehicleBoundDurationSec":"946771200","VehicleInfo":{"VIN":"ZE1-000000","DCMID":"000000000000","SIMID":"0000000000000000000F","NAVIID":"000001000000","EncryptedNAVIID":"FFFFFFFFFFFFFFFFFFFFFFFFF","MSN":"00000000000","LastVehicleLoginTime":"","UserVehicleBoundTime":"2018-12-16T02:47:57Z","LastDCMUseTime":"","custom_sessionid":"0sessionid","NonaviFlg":"false","CarName":"LEAF","CarImage":"carimg2.png"}},"UserInfoRevisionNo":"1","ngTapUpdatebtn":"300000","timeoutUpdateAnime":"300000"}
0



panic: runtime error: index out of range

goroutine 1 [running]:
github.com/joeshaw/carwings.(*Session).Login(0xc000102000, 0xc00008c010, 0x706de7)
        /root/go/src/github.com/joeshaw/carwings/carwings.go:474 +0x565
github.com/joeshaw/carwings.(*Session).Connect(0xc000102000, 0x7ffe84ccc856, 0x6, 0x7ffe84ccc867, 0xa, 0x0, 0x3)
        /root/go/src/github.com/joeshaw/carwings/carwings.go:437 +0x1d4
main.main()
        /root/go/src/github.com/joeshaw/carwings/cmd/carwings/main.go:143 +0x82a

```

**Comment by joeshaw** [comment]
Thanks for the report!  It looks like yet another variation in the `VehicleInfo` information in a response.  I just pushed some code which should fix the issue.
